### ISSUE TITLE
Unable to Fetch RSS Feed

### ISSUE THREAD

**Issue by IamAvneetSK** [smastrom/headless-gatsby-multilang#6]
Most of the services use RSS as the way to get latest articles and content from a website. The inability to get rss.xml file in /public is the issue for my work environment. 
I loved the entire work and will be using the template for sure.

**Comment by smastrom** [comment]
You should be able to configure the plugin [gatsby-plugin-feed](https://www.gatsbyjs.com/plugins/gatsby-plugin-feed/) in order to generate your rss.xml file by following this article: https://meganesulli.com/blog/gatsby-rss-feed/

When you set the input query, just set the DatoCMS one (allDatoCmsBlogPost), the same you can find in the archive JSX template.

To test if everything works, run a build locally and check if the file is created successfully in /public.
