### ISSUE TITLE
[Feature Request] Dark Mode Togggle|Sitemap for Search Engine|Custom Font

### ISSUE THREAD

**Issue by abusayed0206** [smastrom/headless-gatsby-multilang#8]
Could you please add these features to your Gatsby Theme? I'll be very **grateful**.

**Comment by smastrom** [comment]
Hi abusayed,

The sitemap is already generated during build time and available at:

https://headlessmultilingual.gatsbyjs.io/sitemap/sitemap-0.xml

In order to use a custom font, you can place your .woff2 font files under the `/static` folder.

Inside `/src/components/layout/globalStyles.js` import the previously mentioned files:

`import MontserratRegular from '../../../static/montserrat-v18-latin-regular.woff2';`

You should upload one file per font-weight (e.g. 400, 500, 700).

Declare the custom fonts using `@font-face` inside `GlobalStyles`:

```
export const GlobalStyles = createGlobalStyle`

@font-face {
  font-family: Montserrat;
  font-weight: 400;
  font-style: normal;
  src: url(${MontserratRegular}) format('woff2');
  font-display: swap;
}
...
```
You should create one declaration for each weight.

Change the `--defaultStack` CSS variable value inside `:root` selector in the same file from:

`--defaultStack: -apple-system, BlinkMacSystemFont, "Helvetica", "Helvetica Neue", "Arial", sans-serif;`

to:

`--defaultStack: "Montserrat", -apple-system, BlinkMacSystemFont, "Helvetica", "Helvetica Neue", "Arial", sans-serif;`

The custom font will be used globally. If for example you want to use a different weight for a specific element when styling it, set the weight via CSS/styled-components:

```
.newElement {
  font-weight: 700;
}
```

Regarding the dark mode toggle, it is not supported by this starter and you will have to create the feature on your own.

Regards,

smastrom

**Comment by abusayed0206** [comment]
## Thank you SMASTROM❤️!
